### ISSUE TITLE
BinaryBuilder package for libscip

### ISSUE THREAD

**Issue by rschwarz** [scipopt/SCIP.jl#165]
Following [An update on SCIP](http://www.pokutta.com/blog/news/2020/05/15/scip-update.html), I tried putting together a [BinaryBuilder](https://binarybuilder.org/) package for the SCIP libraries, to make installation easier for Julia users.

Alas, my first attempt was not successful, so I will document what I tried so far:

Using `BinaryBuilder.run_wizard()`, I specified the source location [scipoptsuite-7.0.0.tgz](https://scip.zib.de/download/release/scipoptsuite-7.0.0.tgz) and also added several binary dependencies:

- `bliss`: for SCIP symmetry detection
- `boost`: for SoPlex multiprecision floats
- `Ipopt`: for SCIP's global (MI)NLP
- `GMP`: not sure if necessary, exact for ZIMPL and SoPlex rational arithmetic?

I started with the recommended `cmake` incantation given by the wizard. This detected all the expected dependencies, so I could continue with `make`.

----

Then I hit the first error: When building PAPILO, it will also try to build a vendored version of Intel TBB. But the configuration of TBB failed with: `getconf: GNU_LIBC_VERSION: unknown variable`.
Not sure if that is related to the build environment of BB based on an `alpine` Docker image, using `musl`?

I guess it would be best to provide a separate JLL package for Intel TBB, if PAPILO should be added.

----

In any case, I decided to disable some features and compile only the core library with SoPlex and SCIP. That is, I added the `cmake` flags `-DPAPILO=OFF -DZIMPL=OFF -DGCG=OFF`.

But now I got another error from SoPlex: Some static assert failed (forgot to copy), which makes me think that some more recent compiler version is required.

By default, BB uses GCC 4.8.5. It's possible to change the compiler, but I have not yet understood what that means for compatibility with other packages or Julia itself.

**Comment by ericphanson** [comment]
Just to say that this would be great! Also, if you open a PR to Yggdrasil with a non-working build script, often the maintainers will help figure out how to resolve the build issues. (One doesn’t want to abuse this, but it is very helpful!)

**Comment by rschwarz** [comment]
Yeah, I just spent one session with the wizard, but it will probably be more productive to start from a script of a similar project and iterate that way.

**Comment by matbesancon** [comment]
BTW, regarding this: https://www.scipopt.org/doc-5.0.1/html/NLPISOLVERS.php
I just added Ipopt, which is already available through binary builder, so easier overall.

I think I end up at the same error as you:
```
-- Building Intel TBB: /usr/bin/make -j8 stdver=c++14 compiler=gcc extra_inc=big_iron.inc tbb_build_dir=/workspace/srcdir/scipoptsuite-7.0.0/build/papilo tbb_build_prefix=tbb
-- Building is unsuccessful (2): getconf: GNU_LIBC_VERSION: unknown variable
build/common.inc:101: *** "x86_64-linux-gnu" is not supported. Add build/x86_64-linux-gnu.inc or build/x86_64-linux-gnu.linux.inc file.  Stop.
```

**Comment by matbesancon** [comment]
So I think one issue here is that SCIP assumes an Intel architecture, so I think we should restrict the set of compilers, and somehow set GNU_LIBC_VERSION to glibc?

**Comment by matbesancon** [comment]
invoking @giordano in case the error looks familiar (if he's not here I'll ask in BB on Slack later)

**Comment by giordano** [comment]
You should figure out why it's trying to get that variable and work around it, we can't use it in the BinaryBuilder environment

**Comment by giordano** [comment]
> By default, BB uses GCC 4.8.5. It's possible to change the compiler, but I have not yet understood what that means for compatibility with other packages or Julia itself.

For C code, the version of the compiler doesn't tend to matter too much at runtime, as the C library has a good compatibility.  However, note that building a library with gcc version X in general may not not work if a dependent library was built with gcc version Y, with Y > X, because the linker may not appreciate it: https://juliapackaging.github.io/BinaryBuilder.jl/dev/troubleshooting/#Building-with-an-old-GCC-version-a-library-that-has-dependencies-built-with-newer-GCC-versions.

For C++ code, building a library with GCC version X generally (but there might be exception) means that you can't run it on a system with an older libstdc++.  For example, if you build a library with GCC v9 nearly no one will be able to use it, as the official Julia binaries ship the libstdc++ corresponding to GCC v8.  Similar limitations apply to Fortran code.

This is the reason why we try to use the oldest version of GCC to maximise compatibility.  Note that all this applies only GCC, we don't know similar compatibility issues with LLVM, in fact by default we use the latest LLVM version.

**Comment by matbesancon** [comment]
So the culprit is papilo, which requires TBB from Intel. Tricky part is in the papilo/CMakeLists.txt:
```
find_package(TBB MODULE REQUIRED)
if(TBB_BUILT_STATIC_LIB)
   install(FILES ${TBB_STATIC_LIB} DESTINATION lib)
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
   file(TO_CMAKE_PATH "$ENV{TBBROOT}" TBBDLL)
   if (CMAKE_CL_64)
	   install(FILES "${TBBDLL}/../redist/intel64/tbb/vc_mt/tbb.dll" DESTINATION bin)
   else ()
	   install(FILES "${TBBDLL}/../redist/ia32/tbb/vc_mt/tbb.dll" DESTINATION bin)
   endif()
endif()

target_link_libraries(papilo INTERFACE ${TBB_LIBRARY} ${QUADMATH_IMPORTED_TARGET} ${GMP_LIBRARIES})

```

**Comment by giordano** [comment]
I don't see from this snippet how `GNU_LIBC_VERSION` is related

**Comment by matbesancon** [comment]
The error was during the TBB build I think?

**Comment by giordano** [comment]
No idea what the TBB build does :slightly_smiling_face:

**Comment by matbesancon** [comment]
from what I see, it seems to be shipped already built, I will start re-doing the cmake and make for TBB first

**Comment by matbesancon** [comment]
Ok the step happens when make-ing TBB, which is in papilo/external/tbb:
```
sandbox:${WORKSPACE}/srcdir/scipoptsuite-7.0.0/papilo/external/tbb # make
getconf: GNU_LIBC_VERSION: unknown variable
build/common.inc:101: *** "x86_64-linux-gnu" is not supported. Add build/x86_64-linux-gnu.inc or build/x86_64-linux-gnu.linux.inc file.  Stop.
```

The project is this one:
https://github.com/oneapi-src/oneTBB

**Comment by matbesancon** [comment]
There are 3 places this variable seems required in
```
$ ag "GNU_LIBC_VERSION"

external/tbb/build/linux.inc
61:        export os_glibc_version_full:=$(shell getconf GNU_LIBC_VERSION | grep glibc | sed -e 's/^glibc //')

external/tbb/build/version_info_aix.sh
25:echo '#N": BUILD_LIBC'"\t"`getconf GNU_LIBC_VERSION | grep glibc | sed -e 's/^glibc //'`'" ENDL \'

external/tbb/build/version_info_linux.sh
25:echo '#N": BUILD_LIBC'"\t"`getconf GNU_LIBC_VERSION | grep glibc | sed -e 's/^glibc //'`'" ENDL \'
```

**Comment by giordano** [comment]
Yeah, I found it.  I have the feeling the version number of GLIBC doesn't matter at all

**Comment by matbesancon** [comment]
Do you think we can just:
`export GNU_LIBC_VERSION="glibc 2.27"` and continue?

**Comment by giordano** [comment]
It's easier to do `make runtime=...`

**Comment by giordano** [comment]
BTW, the version of GLIBC for each platform is here: https://github.com/JuliaPackaging/Yggdrasil/blob/392eccdea2ba2f7f8755eb3accf852a6c3f35567/RootFS.md#glibc-versions.  However we should probably have it in a variable in `BinaryBuilderBase`

**Comment by matbesancon** [comment]
> make runtime=...

so which argument should be added for runtime here?

**Comment by giordano** [comment]
> Do you think we can just:
> export GNU_LIBC_VERSION="glibc 2.27" and continue?

This wouldn't even work:
```
sandbox:${WORKSPACE} # export GNU_LIBC_VERSION="glibc 2.12.2"
sandbox:${WORKSPACE} # getconf GNU_LIBC_VERSION
getconf: GNU_LIBC_VERSION: unknown variable
```

> so which argument should be added for runtime here?

See how `runtime` is constructed: https://github.com/oneapi-src/oneTBB/blob/427c252e0bb9e191767a62d8a744b21950c343f6/build/linux.inc#L57-L64

**Comment by matbesancon** [comment]
Ok when setting the runtime, the first error disappears:
```
sandbox:${WORKSPACE}/srcdir/scipoptsuite-7.0.0/papilo/external/tbb # make runtime=$runtime 
build/common.inc:101: *** "x86_64-linux-gnu" is not supported. Add build/x86_64-linux-gnu.inc or build/x86_64-linux-gnu.linux.inc file.  Stop.
```

**Comment by giordano** [comment]
What did you use for `runtime`?

**Comment by matbesancon** [comment]
`cc4.8.5_libc2.12.2_kernel5.4.0-42-generic`

**Comment by giordano** [comment]
Discussing here won't work very well.  Please open a PR for Yggdrasil

**Comment by giordano** [comment]
Try with `make runtime=... target=linux`

**Comment by matbesancon** [comment]
will do thank you, I will try to get something working first

**Comment by rschwarz** [comment]
Thanks for giving this another go. I tried 2-3 weeks ago, but there were some SSL issues with the download of the SCIP tarball, which seem to be resolved now.

It might be easier to work with SCIP 7.0.1, which includes some bugfixes for issues that users had with building SCIP on several platforms.

It's also possible to disable PAPILO and drop the TBB dependency. From what I understand, PAPILO is (mostly) used for multi-threaded presolve, so the impact might not be too bad (for now).

**Comment by matbesancon** [comment]
New attempt seems more successful for now:
- SCIP 7.0.1, PAPILO removed for now

**Comment by matbesancon** [comment]
Note, I had an error on SoPlex, that was removed by requiring 5.x as recommended GCC
