### ISSUE TITLE
Evaluate operator when possible

### ISSUE THREAD

**Issue by remi-garcia** [scipopt/SCIP.jl#166]
When an operator such as `cos` in a `NLconstraint` isn't applied to any variable it should not raise an error but just be passed to SCIP as a numerical expression to evaluate (or evaluated in Julia).
``ERROR: Operator cos (in cos(0.0)) not supported by SCIP.jl!``

Obtained with:
```Julia
using JuMP
using SCIP

function main()
    model = Model(SCIP.Optimizer)
    @variable(model, a)
    @NLconstraint(model, a^2 <= cos(0))
    @objective(model, Max, 0)
    optimize!(model)
    return 0
end
```

**Comment by rschwarz** [comment]
I agree that this is possible, but also somewhat tricky. To determine that some sub-expression does not depend on any decision variable, it would first have to be investigated recursively.

**Comment by remi-garcia** [comment]
As a workaround I use this:
```Julia
vector_cos = [cos(operation_on_i(i)) for i in 1:10]
@NLconstraint(model, [i in 1:10], a[i]^2 <= vector_cos[i])
```
To replace this:
```Julia
@NLconstraint(model, [i in 1:10], a[i]^2 <= cos(operation_on_i(i)))
```

Note that replacing `cos` by `my_cos(x) = cos(x)` does not work:
`ERROR: Unrecognized function "my_cos" used in nonlinear expression.`
Since using functions in `@constraint` is not an issue I was surprised to encounter this difficulty with `@NLconstraint`. However this does not really concern `SCIP.jl` but rather `JuMP.jl` or `MathOptInterface.jl`.

**Comment by rschwarz** [comment]
Yes, the workaround is possible.

The difference with `@NLconstraint` is that is passes a Julia `Expr` directly to the solver (if the solver supports it). With `@constraint`, it's transformed into the MOI (function-in-set) form.

So, yes, that's an issue specific to SCIP.jl, see:
https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/src/nonlinear.jl#L118

**Comment by matbesancon** [comment]
I wonder if we could ModelingToolkit for the non-linear part here?
https://mtk.sciml.ai/dev/
Something like doing a pre-processing phase to evaluate some parts and only passing to the solver a simplified NL expression
ping @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Yeah ModelingToolkit would do that just fine. We're trying to get GalacticOptim hooked up to MOI and allow using the symbolic information of MTK which would be the route to SCIP

**Comment by matbesancon** [comment]
OK yes I see, I was thinking whether this project could have its own non-linear preprocessing step but if I'm not mistaken this will require going through the expression, replacing each JuMP variable with an MTK variable, preprocess and convert back

**Comment by ChrisRackauckas** [comment]
MTK can do all of the preprocessing, and GalacticOptim will take an OptimizationSystem from MTK. At this point the issue is more just connecting all of that back to MOI

**Comment by matbesancon** [comment]
Closed with a lazified expression construction, only declare expression when we are hitting a non-pure value node
