### ISSUE TITLE
SCIP and AmplNLWriter

### ISSUE THREAD

**Issue by odow** [scipopt/SCIP.jl#192]
Is there any benefit to using SCIP via https://github.com/jump-dev/AmplNLWriter.jl#scip? Especially since there is now a JLL package.

If there is, how hard is it to modify the JLL to build `scipampl`? If not, I will remove the SCIP section of the AmplNLWriter README.

**Comment by rschwarz** [comment]
I don't know of any benefits. SCIP.jl should support the same range of nonlinear expressions,

**Comment by matbesancon** [comment]
yes I think we can remove it from AMPLNLWriter

**Comment by odow** [comment]
I removed it from the README.
