### ISSUE TITLE
Not building on a fresh Windows 10 installation

### ISSUE THREAD

**Issue by remi-garcia** [scipopt/SCIP.jl#194]
I tried to install julia+SCIP in a VM but it seems that I'm not even able to use Windows 10 properly...
```julia
(@v1.6) pkg> build SCIP
    Building SCIP → `C:\Users\remi\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\65b0334960fc3a068691efaba4ed4d664d3f22a8\build.log`
ERROR: Error building `SCIP`:
ERROR: LoadError: Unable to locate SCIP installation. Tried:

C:\SCIPOptSuite702\bin\libscip.dll: could not load library "C:\SCIPOptSuite702\bin\libscip.dll"
Le module spécifié est introuvable.

C:\SCIPOptSuite702\lib\libscip.dll: could not load library "C:\SCIPOptSuite702\lib\libscip.dll"


libscip.dll: could not load library "libscip.dll"


Note that this must be downloaded separately from scip.zib.de.
Please set the environment variable SCIPOPTDIR to SCIP's installation path.

Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] top-level scope
   @ C:\Users\remi\.julia\packages\SCIP\sQloY\deps\build.jl:56
 [3] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [4] top-level scope
   @ none:5
in expression starting at C:\Users\remi\.julia\packages\SCIP\sQloY\deps\build.jl:55

julia> isfile(ENV["SCIPOPTDIR"]*"\\bin\\libscip.dll")
true
```

- Julia 1.6.1 downloaded today from official website
- SCIP 7.0.2 downloaded today from official website
- Tried with cmd and powershell

The lib file is here, I don't understand why SCIP.jl misses it. If I don't solve this soon, I will start over with a fresh english windows 10 installation in a few days, just in case.

**Comment by remi-garcia** [comment]
I double checked and that's the case:
- julia-1.6.1-win64.exe
- SCIPOptSuite-7.0.2-win64-VS15.exe

**Comment by matbesancon** [comment]
@remi-garcia thanks for the effort! One wild guess is that SCIP.jl expects Ipopt installed? Did you have it on the VM?

**Comment by fschloesser** [comment]
Is there any change to check what the line says where the error comes from? `C:\Users\remi\.julia\packages\SCIP\sQloY\deps\build.jl:55`

**Comment by matbesancon** [comment]
it's the end of this script which tries to find the SCIP location:
https://github.com/scipopt/SCIP.jl/blob/master/deps/build.jl#L55

**Comment by remi-garcia** [comment]
> @remi-garcia thanks for the effort! One wild guess is that SCIP.jl expects Ipopt installed? Did you have it on the VM?

Ipopt is not installed. Yet I installed [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840) and it worked!

<details>
<summary markdown="span">Details</summary>
As @fschloesser suggested I tried `scip.exe` in its /bin folder. This led to two errors (see screenshots 1 and 2). Internet told me that [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840) was missing. I installed it and tried `scip.exe` again, which worked (screenshot 3).

Then I was able to build SCIP in julia 🎉 (screenshot 4)

<details>
<summary markdown="span">Screenshot 1</summary>

![Screenshot from 2021-06-16 16-40-23](https://user-images.githubusercontent.com/47191601/122241577-f4bdf880-cec2-11eb-942a-3012e598776f.png)
</details>
<details>
<summary markdown="span">Screenshot 2</summary>

![Screenshot from 2021-06-16 16-42-44](https://user-images.githubusercontent.com/47191601/122241582-f5568f00-cec2-11eb-8b58-26c54f052dfe.png)
</details>
<details>
<summary markdown="span">Screenshot 3</summary>

![Screenshot from 2021-06-16 16-46-12](https://user-images.githubusercontent.com/47191601/122241586-f5ef2580-cec2-11eb-830a-f796bb9400d7.png)
</details>
<details>
<summary markdown="span">Screenshot 4</summary>

![Screenshot from 2021-06-16 16-47-23](https://user-images.githubusercontent.com/47191601/122241592-f7205280-cec2-11eb-8473-0f1679e64070.png)
</details>
</details>
