### ISSUE TITLE
Constraint handler failing on SCIP 7.0.3

### ISSUE THREAD

**Issue by matbesancon** [scipopt/SCIP.jl#196]
I cross-posted this issue on the SCIP repo:
```julia
# create an empty problem
mscip = SCIP.ManagedSCIP()
SCIP.set_parameter(mscip, "display/verblevel", 0)

# add the constraint handler
ch = NeverSatisfied.NSCH()
SCIP.include_conshdlr(mscip, ch; needs_constraints=false)

# solve the problem
SCIP.@SCIP_CALL SCIP.SCIPsolve(mscip.scip[])

@test ch.check_called >= 1
@test ch.enfo_called == 1
@test ch.lock_called == 1
```

on SCIP `v7.0.3`, `@test ch.enfo_called == 1` fails with 0 on the left-hand side

@rschwarz do you know if something in the NSCH handler could break?

**Comment by rschwarz** [comment]
That's strange, a SCIP bugfix release shouldn't change the behavior w.r.t. callbacks, right?

If I remember correctly, the `NeverSatisfied` constraint handler simply has a `CHECK` callback that always returns `false`.
Maybe the new SCIP has some kind of "shortcut" where the infeasibility of the overall problem can be decided without ever calling the `ENFORCE` method.

**Comment by matbesancon** [comment]
> That's strange, a SCIP bugfix release shouldn't change the behavior w.r.t. callbacks, right?

not really. In that case it did, just in the case when there are no variables left after presolving.

**Comment by matbesancon** [comment]
Closed by enforcing the SCIP version now, and adapted the test in the #195 PR
