### ISSUE TITLE
Get variable and constraint names

### ISSUE THREAD

**Issue by matbesancon** [scipopt/SCIP.jl#204]
Many MOI tests require getting variable and constraint indices by name.

The two solutions are:
1. keep a dictionary of names for each like HiGHS.jl does. Might be simpler to build and test? But we create yet another pair of dicts, this wrapper has a lot of them between SCIP.Optimizer and SCIPData 
2. fetch the names from SCIP directly, see following function:

```c
/** parses the given string for a variable name and stores the variable in the corresponding pointer if such a variable
 *  exits and returns the position where the parsing stopped
 *
 *  @return \ref SCIP_OKAY is returned if everything worked. Otherwise a suitable error code is passed. See \ref
 *          SCIP_Retcode "SCIP_RETCODE" for a complete list of error codes.
 *
 *  @pre This method can be called if @p scip is in one of the following stages:
 *       - \ref SCIP_STAGE_PROBLEM
 *       - \ref SCIP_STAGE_TRANSFORMING
 *       - \ref SCIP_STAGE_INITPRESOLVE
 *       - \ref SCIP_STAGE_PRESOLVING
 *       - \ref SCIP_STAGE_EXITPRESOLVE
 *       - \ref SCIP_STAGE_PRESOLVED
 *       - \ref SCIP_STAGE_SOLVING
 */
SCIP_EXPORT
SCIP_RETCODE SCIPparseVarName(
   SCIP*                 scip,               /**< SCIP data structure */
   const char*           str,                /**< string to parse */
   SCIP_VAR**            var,                /**< pointer to store the problem variable, or NULL if it does not exit */
   char**                endptr              /**< pointer to store the final string position if successful */
   );
```

Opinions? @odow @rschwarz @etadewal

**Comment by matbesancon** [comment]
after trying things for a bit, calling SCIP methods directly seems a bit brittle for now (I'm never sure in which state SCIP is), we'll go for yet anoth dict

**Comment by matbesancon** [comment]
edit from @fserra : `SCIPfindVar` could do the job we want here

**Comment by matbesancon** [comment]
tackled in #205

**Comment by rschwarz** [comment]
I believe this was implemented at some point, letting SCIP store the names. But it lead to errors, so it was removed again. Unfortunately, I can't remember the details. So, *bon courage*!

**Comment by odow** [comment]
Keeping a dictionary isn't too hard. Check the `var_to_name` stuff here: 
https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Utilities/model.jl

**Comment by matbesancon** [comment]
This was done with #205

**Comment by matbesancon** [comment]
it does not yet follow the MOI convention that getting a variable name when several have the same should throw though
