### ISSUE TITLE
SCIP fails when a problem is read from a file

### ISSUE THREAD

**Issue by vladimirvalenta** [scipopt/SCIP.jl#221]
I installed SCIP in VS Code, and I can successfully use it to solve an optimization problem if I formulate the problem directly in Julia/JuMP.

However, when trying to read an existing MIP problem from .mps file (attached), I get the error below. Note that I can solve the same problem easily if I switch set_optimizer to GLPK or Gurobi.

julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 

julia> Pkg.status()
      Status `~/.julia/environments/v1.7/Project.toml`
  [60bf3e95] GLPK v0.15.3
  [2e9cd046] Gurobi v0.10.1
  [4076af6c] JuMP v0.22.2
  [82193955] SCIP v0.10.1
  [9e70acf3] Xpress v0.14.0

```
using JuMP
using GLPK
using Gurobi
using SCIP

model = read_from_file("smallMIP.mps")
set_optimizer(model, SCIP.Optimizer)
optimize!(model)
```

Error:

presolving: (round 1, fast) 475 del vars, 21 del conss, 0 add conss, 21 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 234 clqs (round 2, fast) 938 del vars, 119 del conss, 0 add conss, 21 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 224 clqs (round 3, exhaustive) 938 del vars, 121 del conss, 0 add conss, 21 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 224 clqs (round 4, exhaustive) 938 del vars, 121 del conss, 0 add conss, 21 chg bounds, 0 chg sides, 0 chg coeffs, 224 upgd conss, 0 impls, 224 clqs (0.0s) probing cycle finished: starting next cycle (round 5, exhaustive) 942 del vars, 121 del conss, 0 add conss, 21 chg bounds, 0 chg sides, 0 chg coeffs, 224 upgd conss, 0 impls, 1805 clqs (round 6, fast) 942 del vars, 129 del conss, 0 add conss, 21 chg bounds, 0 chg sides, 0 chg coeffs, 224 upgd conss, 0 impls, 1805 clqs (0.0s) probing: 122/241 (50.6%) - 0 fixings, 4 aggregations, 1663 implications, 0 bound changes (0.0s) probing aborted: 50/50 successive totally useless probings (0.0s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -) dyld: lazy symbol binding failed: Symbol not found: _ZN5bliss13AbstractGraph18find_automorphismsERNS_5StatsEPFvPvjPKjES3 Referenced from: /Users/dudley/.julia/artifacts/61cc42a9d4c8873fe13702e847ac81ef672d40c5/lib/libscip.7.0.dylib Expected in: /Users/dudley/.julia/artifacts/e8e14099d396b38630b2555b46448e3e1c7c476a/lib/libbliss.dylib

dyld: Symbol not found: _ZN5bliss13AbstractGraph18find_automorphismsERNS_5StatsEPFvPvjPKjES3 Referenced from: /Users/dudley/.julia/artifacts/61cc42a9d4c8873fe13702e847ac81ef672d40c5/lib/libscip.7.0.dylib Expected in: /Users/dudley/.julia/artifacts/e8e14099d396b38630b2555b46448e3e1c7c476a/lib/libbliss.dylib

signal (6): Abort trap: 6 in expression starting at /Users/dudley/Documents/Julia/test2.jl:30 strsignal at /usr/lib/system/libsystem_c.dylib (unknown line) jl_critical_error at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line) sigdie_handler at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line) _sigtramp at /usr/lib/system/libsystem_platform.dylib (unknown line) unknown function (ip: 0x0) Allocations: 34026932 (Pool: 34018136; Big: 8796); GC: 34 (0.1s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -) dyld: lazy symbol binding failed: Symbol not found: _ZN5bliss13AbstractGraph18find_automorphismsERNS_5StatsEPFvPvjPKjES3 Referenced from: /Users/dudley/.julia/artifacts/61cc42a9d4c8873fe13702e847ac81ef672d40c5/lib/libscip.7.0.dylib Expected in: /Users/dudley/.julia/artifacts/e8e14099d396b38630b2555b46448e3e1c7c476a/lib/libbliss.dylib

dyld: Symbol not found: _ZN5bliss13AbstractGraph18find_automorphismsERNS_5StatsEPFvPvjPKjES3 Referenced from: /Users/dudley/.julia/artifacts/61cc42a9d4c8873fe13702e847ac81ef672d40c5/lib/libscip.7.0.dylib Expected in: /Users/dudley/.julia/artifacts/e8e14099d396b38630b2555b46448e3e1c7c476a/lib/libbliss.dylib
[SmallSudoku.mps.zip](https://github.com/scipopt/SCIP.jl/files/8104935/SmallSudoku.mps.zip)

**Comment by iSoron** [comment]
@vladimirvalenta We ran into the same issue. It appears that SCIP.jl requires `bliss_jll` v0.73, but Julia is automatically installing a newer version, which is not compatible. A workaround is to manually install the older version of `bliss_jll` as follows:
```
using Pkg
Pkg.add(PackageSpec(name="bliss_jll", version="0.73"))
```
A more proper solution would be to specify the `bliss_jll` version in the [SCIP_jll build_tarballs script](https://github.com/JuliaPackaging/Yggdrasil/blob/5116ea8e918fdd6825495a7a6df437fa1ebcd87d/S/SCIP/build_tarballs.jl#L53).

**Comment by vladimirvalenta** [comment]
@iSoron Thank you so much, that did the trick!

**Comment by matbesancon** [comment]
thanks this is good to know, I'll update the specifications in SCIP_jll for this
