### ISSUE TITLE
How to trigger SCIPsolveConcurrent?

### ISSUE THREAD

**Issue by freemin7** [scipopt/SCIP.jl#238]
SCIP provides concurrent solving [https://www.scipopt.org/doc-5.0.1/html/CONCSCIP.php](https://www.scipopt.org/doc-5.0.1/html/CONCSCIP.php). How would i go about triggering it?

**Comment by matbesancon** [comment]
First thing would be to compile SCIP with the suitable options.

Second would be to modify slightly the optimize! function to call SCIPsolveConcurrent instead of SCIPsolve here:

```julia
function MOI.optimize!(o::Optimizer)
    set_start_values(o)
    if o.objective_sense == MOI.FEASIBILITY_SENSE
        MOI.set(o, MOI.ObjectiveFunction{SAF}(), SAF([], 0.0))
    end
    @SCIP_CALL SCIPsolve(o)
    return nothing
end
```

**Comment by matbesancon** [comment]
PS: up to date documentation page is here:
https://www.scipopt.org/doc-8.0.1/html/CONCSCIP.php

**Comment by matbesancon** [comment]
I'll close this one for https://github.com/scipopt/SCIP.jl/issues/242 which is similar.
