### ISSUE TITLE
Not solving the optimization model with the SCIP solver

### ISSUE THREAD

**Issue by karimianfard** [scipopt/SCIP.jl#281]
Hello. I have successfully installed the SCIP solver on Windows 10 and on Julia and on a Jupiter notebook. But when I try to solve my model, I face the following problem (according to the picture):
Please note that this same model is easily solved by all my other solvers like Gurobi, CBC and GLPK without such error!

![Untitled](https://github.com/scipopt/SCIP.jl/assets/84530547/80740bd4-a122-420e-bbfe-436a853eb848)

Solved the same model with Gurobi solver! please guide me:

![image](https://github.com/scipopt/SCIP.jl/assets/84530547/f8faa802-c26c-4c83-bc3e-cba91cbda36d)

**Comment by matbesancon** [comment]
Hello, did you install SCIP separately from the Julia package?
See the instructions here: https://github.com/scipopt/SCIP.jl#custom-installations

**Comment by karimianfard** [comment]
Dear Mathieu Besançon @matbesancon 

Yes I have installed the latest version of SCIP separately.

**Comment by matbesancon** [comment]
Can you do "using SCIP" in a Julia session and see if it also kills the session?
I would invite you to check the other issues opened for Windows:
https://github.com/scipopt/SCIP.jl/issues?q=is%3Aissue+Windows+

**Comment by karimianfard** [comment]
Yes I easily do this command "using SCIP" and there are no errors. Only by defining the variables and solving the problem you will get the mentioned error.
Please see the figure below: The command "optimize!(model)" that I type faces the problem of solving.
![image](https://github.com/scipopt/SCIP.jl/assets/84530547/1601e406-9d62-4295-ac81-2f4182936d17)

**Comment by karimianfard** [comment]
![image](https://github.com/scipopt/SCIP.jl/assets/84530547/53cc5d81-7584-4b7e-bf3c-d50f66ba94cc)

**Comment by karimianfard** [comment]
Does anyone know where the problem is?

**Comment by matbesancon** [comment]
Can you try:
```
o = SCIP.Optimizer()
```

**Comment by karimianfard** [comment]
Dear @matbesancon 

Which line should I replace this command with? My model is below:

```
using JuMP, SCIP
model = Model(SCIP.Optimizer)
set_attribute(model, "display/verblevel", 0)
set_attribute(model, "limits/gap", 0.05)
@variable((model), x);
@variable((model), y);
@objective((model), Min, (x) + (y));
@constraint((model), x >= 0)
@constraint((model), y >= 5)
optimize!(model)
println(value.(x))
println(value.(y))
```

**Comment by matbesancon** [comment]
Just
using SCIP
@show @eval SCIP libscip
o = SCIP.Optimizer()

As an alternative attempt, please run the code that you already have but
without the line setting verblevel to 0. You can do both.

Thanks!

**Comment by matbesancon** [comment]
The path of libscip is in `.julia/artifacts`, which means SCIP was not installed or recognized. 
Please follow the similar steps as in this issue: https://github.com/scipopt/SCIP.jl/issues/248

**Comment by karimianfard** [comment]
The problem was solved. Thanks.
