### ISSUE TITLE
Update to allow SCIP version 9?

### ISSUE THREAD

**Issue by GregPlowman** [scipopt/SCIP.jl#286]
Can SCIP.jl be updated to allow SCIP version 9.

It seems there are version 9 `jll`s for SCIP and SCIP_PaPILO:
```
SCIP_jll 900.0.0+1
SCIP_PaPILO_jll 900.0.0+0
```

Currently, SCIP version is limited in `init.jl`:
```
current = VersionNumber("$major.$minor.$patch")
required = VersionNumber("8")
upperbound = VersionNumber("9")
if current < required || current >= upperbound
    @error(
        "SCIP is installed at version $current, " *
        "supported are $required up to (excluding) $upperbound."
    )
end
```
Note that `current >= upperbound` results in the error.
Manually editing to `current > upperbound` seems to work with a manual installation of SCIP version 9, which is required for Windows.

**Comment by matbesancon** [comment]
fixed in recent PR
