### ISSUE TITLE
Version mismatch error (version is 8.0.3 but 9-10 is required)

### ISSUE THREAD

**Issue by resmaeilbeigi** [scipopt/SCIP.jl#295]
I am getting this error once I updated a julia environment which updated SCIP `v0.11.14 ⇒ v0.12.0`

Is this related to https://github.com/scipopt/SCIP.jl/issues/286?

On a side note, the documentation says
`On platforms other than Windows, in addition to installing the SCIP.jl package, this will also download and install the SCIP binaries. You do not need to install SCIP separately.`

I'm using Ubuntu with Julia 1.11.1 and running `Pkg.add("SCIP")` does not download the binaries. Neither does the update mentioned above download the new binaries (which I expected to happen).

**Comment by matbesancon** [comment]
Did you update the whole environment? I just tested and the update does work on a linux machine

> I'm using Ubuntu with Julia 1.11.1 and running Pkg.add("SCIP") does not download the binaries

It is using SCIP_jll which contains the binaries directly as artifacts

**Comment by resmaeilbeigi** [comment]
Thanks, I just re-tried and the error is gone. Maybe because I had closed vscode and I just re-opened it (I have had a lot of issues with Julia in vscode). So in summary, after re-starting vscode, I updated all packages in the environment:
```
julia> Pkg.update()
    Updating registry at `~/workspace_test/cyclone2/julia-packages/1.11.1/registries/General.toml`
    Updating `~/workspace_test/cyclone2/Project.toml`
  [4076af6c] ↑ JuMP v1.23.2 ⇒ v1.23.3
  [b8f27783] ↑ MathOptInterface v1.31.2 ⇒ v1.32.0
  [82193955] ↑ SCIP v0.11.14 ⇒ v0.12.0
    Updating `~/workspace_test/cyclone2/Manifest.toml`
  [4076af6c] ↑ JuMP v1.23.2 ⇒ v1.23.3
  [b8f27783] ↑ MathOptInterface v1.31.2 ⇒ v1.32.0
  [82193955] ↑ SCIP v0.11.14 ⇒ v0.12.0
⌅ [9cc047cb] ↑ Ipopt_jll v300.1400.1302+0 ⇒ v300.1400.1400+0
⌅ [d7ed1dd3] ↑ MUMPS_seq_jll v500.600.100+0 ⇒ v500.600.201+0
  [fc9abe76] ↑ SCIP_PaPILO_jll v800.100.0+0 ⇒ v900.0.0+0
  [e5ac4fe4] ↑ SCIP_jll v800.100.0+1 ⇒ v900.0.0+1
⌅ [319450e9] ↑ SPRAL_jll v2023.8.2+0 ⇒ v2024.1.18+0
```
After this update, I can confirm that the environment variable `SCIPOPTDIR` is `/opt/SCIP` directory which contains SCIP version `8.0.3` and I can optimise with this SCIP version without any issue (I have to use this specific version for now). I also noticed that the package `SCIP_jll` is not installed, i.e., when I run `using SCIP_jll` in a julia session, it says
```
julia> using SCIP_jll
 │ Package SCIP_jll not found, but a package named SCIP_jll is available from a registry. 
 │ Install package?
 │   (cyclone2) pkg> add SCIP_jll 
 └ (y/n/o) [y]: 
```
Not sure how SCIP determines which SCIP to use and when to install/use `SCIP_jll` (perhaps becuase SCIPOPTDIR was set before the update above)

**Comment by matbesancon** [comment]
the automatic version you install in `/opt/SCIP` is a manual installation right? You don't need SCIP_jll installed explicitly by you, it gets downloaded by SCIP.jl automatically because SCIP depends on it.
You can check the Pkg docs for how package management works in Julia: https://pkgdocs.julialang.org/v1/
