### ISSUE TITLE
Support MOI.delete for variables that participate in constraints.

### ISSUE THREAD

**Issue by rschwarz** [scipopt/SCIP.jl#90]
See #85 for previous issue and #88 for discussion.

This requires upstream changes in SCIP itself.

**Comment by rschwarz** [comment]
I don't know whether anything was changed on the SCIP side (and don't even remember the linked discussion).
Back then, I was able to trigger an `assert` in SCIP using [this gist](https://gist.github.com/rschwarz/4a64a7a690a44919d3ec88330021405b) written in C.

**Comment by matbesancon** [comment]
this is still triggered on SCIP master it seems. This has never been an intended / documented behaviour I assume

**Comment by matbesancon** [comment]
I opened an issue on SCIP itself to track this. If this is "intended" / documented behavior, one solution would be to loop through constraints to delete them before deleting the variable. Not sure what are other solvers' conventions for this
